// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockAPI.Models;

public partial class CashFlowStatement
{
    public int Id { get; set; }

    public string CompanyCode { get; set; }

    public int? Year { get; set; }

    public int? Season { get; set; }

    public decimal? OperatingCashFlow { get; set; }

    public decimal? InvestingCashFlow { get; set; }

    public decimal? FinancingCashFlow { get; set; }

    public decimal? ExchangeRateEffect { get; set; }

    public decimal? NetChangeInCash { get; set; }

    public decimal? BeginningCash { get; set; }

    public decimal? EndingCash { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Company CompanyCodeNavigation { get; set; }
}