// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockAPI.Models;

public partial class IncomeStatement
{
    public int Id { get; set; }

    public string CompanyCode { get; set; }

    public int? Year { get; set; }

    public int? Season { get; set; }

    public decimal? Revenue { get; set; }

    public decimal? OperatingCosts { get; set; }

    public decimal? GrossProfit { get; set; }

    public decimal? UnrealizedProfit { get; set; }

    public decimal? RealizedProfit { get; set; }

    public decimal? NetGrossProfit { get; set; }

    public decimal? OperatingExpenses { get; set; }

    public decimal? OtherIncomeExpenses { get; set; }

    public decimal? OperatingIncome { get; set; }

    public decimal? NonOperating { get; set; }

    public decimal? PreTaxIncome { get; set; }

    public decimal? IncomeTax { get; set; }

    public decimal? ContinuingOperationsIncome { get; set; }

    public decimal? DiscontinuedOperations { get; set; }

    public decimal? NonControllingPreMerger { get; set; }

    public decimal? NetIncome { get; set; }

    public decimal? OtherComprehensiveIncome { get; set; }

    public decimal? NonControllingComprehensive { get; set; }

    public decimal? TotalComprehensiveIncome { get; set; }

    public decimal? NetIncomeParent { get; set; }

    public decimal? NetIncomePriorControl { get; set; }

    public decimal? NetIncomeNonControlling { get; set; }

    public decimal? ComprehensiveIncomeParent { get; set; }

    public decimal? ComprehensiveIncomePriorControl { get; set; }

    public decimal? ComprehensiveIncomeNonControlling { get; set; }

    public decimal? Eps { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Company CompanyCodeNavigation { get; set; }
}